[tool.poetry]
name = "neo4j-uploader-gcf"
version = "0.1.0"
description = ""
authors = ["Jason Koo <jalakoo@gmail.com>"]
readme = "README.md"
packages = [{include = "neo4j_uploader_gcf"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"
neo4j-uploader = ">=0.3,<1.0"
functions-framework = "^3.4.0"
neo4j = "^5.14.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
